[build]
command = "npm run build"
publish = ".next"

[functions]
  included_files = [".next/*.json"]
  
[[plugins]]
package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/api/v2/*"
  to = "https://uat-gar-platform-master-web.unataops.com/api/v2"
  status = 200
  force = true

[[redirects]]
  from = "/frontend-config.js"
  to = "https://uat-gar-platform-master-web.unataops.com/frontend-config.js"
  status = 200
  force = true

[[redirects]]
  from = "/env-config.js"
  to = "https://uat-gar-platform-master-web.unataops.com/env-config.js"
  status = 200
  force = true